version: '3'

services:

  web:
    build: .
    command: uvicorn server.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ciplay
    depends_on:
      - db

  db:
    image: postgres:alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ciplay
